### ISSUE TITLE
script doesn't work with python3.x

### ISSUE THREAD

**Issue by irfan-m-mohammad** [minkustree/socket-throttle#1]
`_fileobject` attribute is not supported by python3.x
tried to change to [#L104](https://github.com/minkustree/socket-throttle/blob/master/socket-throttle.py#L104) to use `socket.SocketIO` but it doesn't seem to work. 
error:
`line 63, in makefile
    return socket.SocketIO(self, mode, bufsize)
TypeError: __init__() takes 3 positional arguments but 4 were given`
Please help update the script to run on python 3

**Comment by minkustree** [comment]
I'm sorry, but there seem to have been too many changes in the ways that sockets work from Python 2 to 3 to make it possible for me to make this work with Python 3. 

I no longer have a need for this code, so won't be maintaining it any further.

**Comment by irfan-m-mohammad** [comment]
Can you provide any pointers on how to implement this for python 3?

**Comment by minkustree** [comment]
When I implemented it for python 2, I traced through what methods would be called when receiving data from a socket in a httplib client connection, and then used that information to decide what socket methods to override. 

I don't know enough about how Python 3 sockets work to do the same, so I'm afraid I cannot offer any more help than that. Good luck!
